name = "memory-weaver-test"
main = "functions/simple-memory-handler.js" 
compatibility_date = "2024-01-01"

# Account configuration
account_id = "6e794c040a03d9cc6aaa6bcc3462f0cb"

# No bindings - just test deployment 