name = "memory-weaver-workers"
main = "functions/main-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Account configuration  
account_id = "6e794c040a03d9cc6aaa6bcc3462f0cb"

# Environment variables
[env.development.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
IPFS_NODE_URL = "http://31.220.107.113:5001/"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
IPFS_NODE_URL = "http://31.220.107.113:5001/"

# Production environment D1 database binding
[[env.production.d1_databases]]
binding = "MEMORY_DB"
database_name = "memory-weaver-db"
database_id = "ff259898-64db-4446-896d-ca2e64a54034"

# Production environment KV namespace
[[env.production.kv_namespaces]]
binding = "UPLOAD_SESSIONS"
id = "a4b678475e8f411da6bc8628771c0ddb"
preview_id = "a4b678475e8f411da6bc8628771c0ddb"

# Production environment R2 bucket
[[env.production.r2_buckets]]
binding = "MEMORY_FILES"
bucket_name = "memory-weaver-files"

# Development environment bindings (fallback)
# D1 database binding for metadata
[[d1_databases]]
binding = "MEMORY_DB"
database_name = "memory-weaver-db"
database_id = "ff259898-64db-4446-896d-ca2e64a54034"

# KV namespace for session management
[[kv_namespaces]]
binding = "UPLOAD_SESSIONS"
id = "a4b678475e8f411da6bc8628771c0ddb"
preview_id = "a4b678475e8f411da6bc8628771c0ddb"

# R2 bucket for file storage
[[r2_buckets]]
binding = "MEMORY_FILES"
bucket_name = "memory-weaver-files" 